import type { Metadata } from "next";
import Navbar from "./settings/_components/navbar";
export const metadata: Metadata = {
	title: "Create Auth System",
	description: "Generated by create next app",
};

interface ProtectedLayoutProps {
	children: React.ReactNode;
}
const ProtectedLayout = ({ children }: ProtectedLayoutProps) => {
	return (
		<div className="h-full w-full flex flex-col gap-y-10 items-center    bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800">
			<Navbar />
			{children}
		</div>
	);
};

export default ProtectedLayout;
